[tool.poetry]
name = "moz-books"
version = "0.1.0"
description = "mozkzki's book service library."
authors = ["mozkzki <mozkzki@gmail.com>"]
maintainers = ["mozkzki <mozkzki@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/mozkzki/moz-books"
repository = "https://github.com/mozkzki/moz-books"
documentation = "https://github.com/mozkzki/moz-books/wiki"
keywords = ['book', 'rakuten', 'calil']
classifiers=[
    'Development Status :: 3 - Alpha',
    'License :: OSI Approved :: MIT License',
    'Topic :: Software Development :: Libraries',
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
]

[tool.poetry.dependencies]
python = "^3.7"
python-dotenv = "0.21.1"
requests = "2.28.2"
coloredlogs = "15.0.1"

[tool.poetry.dev-dependencies]
flake8 = "5.0.4"
mypy = "1.0.1"
pytest = "7.2.1"
black = "23.1.0"
pytest-cov = "4.0.0"
coverage = "7.2.1"
isort = "5.11.5"
Sphinx = "4.3.2"
sphinx-rtd-theme = "1.2.0"
types-requests = "2.28.11.14"
pytest-env = "0.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
